name: Build and Deploy

on:
  push:
    branches:
      - '**'
      - '!main'

run-name: "Branch name: ${{ github.ref_name }}, Environment name: ${{ github.short_sha }} run by @${{ github.actor }}"

jobs:
  build:
    name: "Branch: ${{ github.ref_name }}, Env: ${{ github.event.inputs.env_name }}"
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting build environment
        run: |
            echo "TAG=${{ github.short_sha }}" >> $GITHUB_ENV

      - name: List Env Variables
        run: |
          env
          cat $GITHUB_ENV

      - name: Print some variables
        run: |
          echo ${{ github.short_sha }}
          echo ${{ github.sha }}
          cat $GITHUB_ENV

