name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Env name to deploy'
        required: true

env:
  PROJECT_ID: engineering-400113
  GAR_LOCATION: us-central1
  ENVIRONMENT: dev
  INSTANCE_IP: 34.123.5.212
  PROJECT_NAME: zerobroker
  REPO: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build and Deploy
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Setting build environment
        run: |
          if [[ ${{ github.event.inputs.env_name }} == "prod" ]]; then
            echo "Building Production Backend Image"
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "PROJECT_ID=hubtech-dev-246811" >> $GITHUB_ENV
            echo "INSTANCE_IP=34.31.65.146" >> $GITHUB_ENV
          fi

      - name: List Env Variables
        run: |
          env
          cat $GITHUB_ENV

      - name: Print some variables
        run: |
          echo ${{ github.event.repository.name }}
          cat $GITHUB_ENV
