name: Build and Deploy

on:
  push:
    branches:
      - '**'
      - '!main'

run-name: "Br: ${{ github.ref_name }}, SHA: ${{ github.sha }} run by @${{ github.actor }}"

jobs:
  build:
    name: "test"
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting build environment
        run: |
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: List Env Variables
        run: |
          env
          cat $GITHUB_ENV

      - name: Print some variables
        run: |
          echo ${{ env.TAG }}
          echo ${{ github.sha }}
          cat $GITHUB_ENV

