name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name (for manual dispatch)'
        required: true

env:
  PROJECT_ID: engineering-400113
  GAR_LOCATION: us-central1
  ENVIRONMENT: dev
  INSTANCE_IP: 34.123.5.212
  PROJECT_NAME: zerobroker

jobs:
  build:
    if: github.ref == 'refs/heads/${{ github.event.repository.default_branch }}' || github.event_name == 'workflow_dispatch'
    name: Build and Deploy
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch_name || github.ref }}

      - name: Setting build environment
        run: |
          if [[ ${{ github.ref }} == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            echo "Building Production Backend Image"
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "PROJECT_ID=hubtech-dev-246811" >> $GITHUB_ENV
            echo "INSTANCE_IP=34.31.65.146" >> $GITHUB_ENV
          fi

      - name: List Env Variables
        run: env

