name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name (for manual dispatch)'
        required: true

env:
  PROJECT_ID: engineering-400113
  GAR_LOCATION: us-central1
  ENVIRONMENT: dev
  INSTANCE_IP: 34.123.5.212
  PROJECT_NAME: zerobroker
  REPO: ${{ github.event.repository.name }}

jobs:
  build:
    if: github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    name: Build and Deploy
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch_name || 'main' }}

      - name: Setting build environment
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name || 'main' }}"
          if [[ "$BRANCH_NAME" == 'main' ]]; then
            echo "Building Production Backend Image"
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "PROJECT_ID=hubtech-dev-246811" >> $GITHUB_ENV
            echo "INSTANCE_IP=34.31.65.146" >> $GITHUB_ENV
          fi

      - name: List Env Variables
        run: env

      - name: Print some variables
        run: |
          echo ${{ github.event.repository.name }}
          cat $GITHUB_ENV
